// AUTO-GENERATED by scripts/parse-places.py — DÜZENLEME yapma, kaynak:
// /Users/.../Takeout/Haritalar (yerleriniz)/*.json
// places: 5 | countries: ['KR']

window.PLACES = [
  {
    "id": "p_c57acc92974a",
    "name": "Changdeokgung",
    "address": "99 Yulgok-ro, Jongno District, Seoul, Güney Kore",
    "country": "KR",
    "city": "Seoul",
    "type": "Tarihi",
    "typeEmoji": "🏯",
    "lat": 37.5794309,
    "lng": 126.9910426,
    "googleUrl": "http://maps.google.com/?cid=18386345253664084072",
    "comment": null,
    "source": "Kaydedilen Yerler.json"
  },
  {
    "id": "p_054fd676114c",
    "name": "Gyeongbokgung",
    "address": "161 Sajik-ro, Jongno District, Seoul, Güney Kore",
    "country": "KR",
    "city": "Seoul",
    "type": "Tarihi",
    "typeEmoji": "🏯",
    "lat": 37.579617,
    "lng": 126.977041,
    "googleUrl": "http://maps.google.com/?cid=10029593693201569270",
    "comment": null,
    "source": "Kaydedilen Yerler.json"
  },
  {
    "id": "p_1e2ace74a432",
    "name": "M Playground",
    "address": "16-1 Myeongdong 10-gil, Jung District, Seoul, Güney Kore",
    "country": "KR",
    "city": "Seoul",
    "type": "Eğlence",
    "typeEmoji": "🎢",
    "lat": 37.5627055,
    "lng": 126.985299,
    "googleUrl": "http://maps.google.com/?cid=15284869606283330708",
    "comment": null,
    "source": "Kaydedilen Yerler.json"
  },
  {
    "id": "p_d77a5ac15083",
    "name": "Naksan Park",
    "address": "41 Naksan-gil, Jongno District, Seoul, Güney Kore",
    "country": "KR",
    "city": "Seoul",
    "type": "Park & Doğa",
    "typeEmoji": "🌳",
    "lat": 37.5806571,
    "lng": 127.0074835,
    "googleUrl": "http://maps.google.com/?cid=11484851618044523613",
    "comment": null,
    "source": "Kaydedilen Yerler.json"
  },
  {
    "id": "p_f94288bf23f1",
    "name": "Seoul City Wall Trail",
    "address": "622-83 Changsin-dong, Jongno District, Seoul, Güney Kore",
    "country": "KR",
    "city": "Seoul",
    "type": "Tarihi",
    "typeEmoji": "🏯",
    "lat": 37.5779633,
    "lng": 127.0084459,
    "googleUrl": "http://maps.google.com/?cid=11962570967396647457",
    "comment": null,
    "source": "Kaydedilen Yerler.json"
  }
];

window.PLACE_COUNTRIES = [
  {
    "code": "KR",
    "label": "Güney Kore",
    "cities": [
      {
        "name": "Seoul",
        "count": 5
      }
    ],
    "total": 5
  }
];
